services:
  
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - PG_DB=example
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    networks:
      - spring-postgres
  
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres:
